### ISSUE TITLE
File List is empty 

### ISSUE THREAD

**Issue by TienDungHUST** [stjuliet/Labelimg3D#1]
I think the SVLD make the model overfiting, therefore I try to conduct my own dataset by this tool. I run the .exe (version2) on Windows but got nothing on _File List_ frame. Some images in folder are available. Why it doesn't work? 
Please give me some instructions. Thank you,

**Comment by stjuliet** [comment]
> I think the SVLD make the model overfiting, therefore I try to conduct my own dataset by this tool. I run the .exe (version2) on Windows but got nothing on _File List_ frame. Some images in folder are available. Why it doesn't work? Please give me some instructions. Thank you,

Thank you for your attention. Perhaps you need to download the pretrained yolov4 model (release: https://github.com/stjuliet/Labelimg3D/releases/tag/yolov4-model-highway) for detection into the "model_us_yolov4" folder, which is in the same directory with the exe file.
It is suggested to install this tool from source code (instruction: https://github.com/stjuliet/Labelimg3D/blob/master/INSTALL.md), for finding problems more easily.

**Comment by TienDungHUST** [comment]
Thank for your quick response, 
1st, I put the yolov4 model at the same dir with the .exe file. It doesn't work.
2nd, I carefully install this tool by source code in  Windows 10 with conda environment following the instruction in `INSTALL.md`. 
The command `python main.py` doesn't raise any error, then the windows pop-up. However I face to the same issue as above. Have no file appears on FILE LIST frame after I chose the image folder. It look like this picture. Do you have any advice?
![image](https://user-images.githubusercontent.com/77160942/182346558-f7f1020e-3037-484e-b983-a3030d4aa0c6.png)
@stjuliet

**Comment by TienDungHUST** [comment]
It works after I put the calib file in the same folder of images. Thank you.
